# Generated by Django 4.2.6 on 2023-11-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='province',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
