# Generated by Django 4.2.6 on 2023-11-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useradditionalinfo_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='phone_number1',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='phone_number2',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
