version: '3'
networks:
  tekana-network:
    external: true
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - tekana-network
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - celery

  postgres:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: tekana
      POSTGRES_USER: tekanauser
      POSTGRES_PASSWORD: tekanapassword
    networks:
      - tekana-network
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - tekana-network
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A TekanaEwallet  worker -l INFO --pool=prefork -O fair -c 4"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
