version: '3'
services:
  web:
    image: "tekana"
    container_name: "tekana_ewallet"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      SECRET_KEY: f*-_v^reor&(_#@#*#aug0k=p8142raif7k43v0nyd&-s#
      DB_ENGINE: django.contrib.gis.db.backends.postgis
      DB_NAME: tekanadb
      DB_USER: tekanauser
      DB_PASSWORD: tekanapassword
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: tekanadb
      POSTGRES_USER: tekanauser
      POSTGRES_PASSWORD: tekanapassword
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # Celery worker
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A TekanaEwallet worker -l info"
    depends_on:
      - db
      - redis
      - web
    restart: on-failure
