openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/users/:
    get:
      operationId: listUsers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
    post:
      operationId: createUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
  /api/v1/users/{id}/:
    get:
      operationId: retrieveUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this user.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
    put:
      operationId: updateUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this user.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this user.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this user.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/v1/account/:
    get:
      operationId: listAccounts
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
          description: ''
      tags:
      - api
    post:
      operationId: createAccount
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Account'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
          description: ''
      tags:
      - api
  /api/v1/account/activity/:
    get:
      operationId: getAccountActivityAccount
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountActivity'
          description: ''
      tags:
      - api
  /api/v1/account/transactions/:
    get:
      operationId: getTransactionsAccount
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
      tags:
      - api
  /api/v1/account/{id}/:
    get:
      operationId: retrieveAccount
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this account.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
          description: ''
      tags:
      - api
    put:
      operationId: updateAccount
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this account.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Account'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateAccount
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this account.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Account'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyAccount
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this account.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/auth/login/:
    post:
      operationId: createJWTToken
      description: Login handler
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JWTToken'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/JWTToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/JWTToken'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTToken'
          description: ''
      tags:
      - api
  /api/auth/refresh/:
    post:
      operationId: createTokenRefresh
      description: Refresh token handler which extends TokenRefresh from simple jwt
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
      tags:
      - api
  /api/auth/verify/:
    post:
      operationId: createTokenVerify
      description: Verify token handler which extends TokenRefresh from simple jwt
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenVerify'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenVerify'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenVerify'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenVerify'
          description: ''
      tags:
      - api
  /api/v1/users/activate-account/:
    post:
      operationId: activateAccountUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OTP'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OTP'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OTP'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OTP'
          description: ''
      tags:
      - api
  /api/v1/users/create-account/:
    post:
      operationId: createAccountUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreate'
          description: ''
      tags:
      - api
  /api/v1/account/transact/:
    post:
      operationId: transferFundsAccount
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferFunds'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TransferFunds'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TransferFunds'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferFunds'
          description: ''
      tags:
      - api
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        first_name:
          type: string
          maxLength: 100
        middle_name:
          type: string
          nullable: true
          maxLength: 100
        last_name:
          type: string
          maxLength: 100
        email:
          type: string
          format: email
          maxLength: 254
        identification_type:
          enum:
          - NID
          - PSP
          type: string
        identification:
          type: string
          nullable: true
          maxLength: 100
        dob:
          type: string
          format: date
          nullable: true
        active:
          type: boolean
        joined_on:
          type: string
          format: date-time
          readOnly: true
        updated_on:
          type: string
          format: date-time
          readOnly: true
      required:
      - first_name
      - last_name
      - email
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        account_id:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        currency:
          type: string
          nullable: true
          maxLength: 4
        balance:
          type: number
        description:
          type: string
        created_on:
          type: string
          format: date-time
          readOnly: true
        updated_on:
          type: string
          format: date-time
          readOnly: true
        user:
          type: string
      required:
      - account_id
      - balance
      - description
      - user
    AccountActivity:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        current_balance:
          type: number
        balance:
          type: number
        activity_type:
          enum:
          - PULL
          - PUSH
          - RECEIVE
          type: string
        created_on:
          type: string
          format: date-time
          readOnly: true
        updated_on:
          type: string
          format: date-time
          readOnly: true
        account:
          type: string
      required:
      - current_balance
      - balance
      - account
    Transaction:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        receiver:
          type: string
          readOnly: true
        amount:
          type: number
        description:
          type: string
        transanction_time:
          type: string
          format: date-time
          readOnly: true
      required:
      - amount
      - description
    JWTToken:
      type: object
      properties:
        email:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
      required:
      - email
      - password
    TokenRefresh:
      type: object
      properties:
        refresh:
          type: string
        access:
          type: string
          readOnly: true
      required:
      - refresh
    TokenVerify:
      type: object
      properties:
        token:
          type: string
          writeOnly: true
      required:
      - token
    OTP:
      type: object
      properties:
        otp:
          type: integer
      required:
      - otp
    UserCreate:
      type: object
      properties:
        first_name:
          type: string
          maxLength: 100
        last_name:
          type: string
          maxLength: 100
        identification_type:
          enum:
          - NID
          - PSP
          type: string
        identification:
          type: string
          nullable: true
          maxLength: 100
        email:
          type: string
          format: email
          maxLength: 254
        password:
          type: string
          writeOnly: true
      required:
      - first_name
      - last_name
      - email
      - password
    TransferFunds:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        receiver:
          type: string
          nullable: true
        amount:
          type: number
        description:
          type: string
        transanction_time:
          type: string
          format: date-time
          readOnly: true
      required:
      - receiver
      - amount
      - description
